### PR TITLE
Fix LfgAction

### PR DESCRIPTION
**Pull request by EricksOliveira**
Fix Bot Leave PT in Join Dungeon.

### CODE REVIEW

**Comment by EricksOliveira** [comment]
> This will cause random robots to remain in the team. If the player quits, the robot cannot be teamed up with other players. This is not in line with normal player behavior.

Couldn't identify this problem. But I will carry out some more tests.

**Comment by hermensbas** [comment]
Any progression or should this PR be on draft?

**Comment by EricksOliveira** [comment]
Yes. I had a great recovery. However, I ask that you wait a little longer, as I am doing more tests regarding the specs and searches in the DG. More in relation to DG's Bot Kitar, it was resolved. I'm just improving the code. Time is too short for me to work constantly.

**Comment by hermensbas** [comment]
hehe, yup time time. No hurry right? I will set on draft you can turn switch from draft once your rdy. So it doesnt get merged by mistake while ur not rdy.

**Pull request merged**
