### PR TITLE
Handle bot gear upgrades for multi-slot items

### PR DESCRIPTION
**Pull request by Bobblybook**
Switch to using opcode "CMSG_AUTOEQUIP_ITEM_SLOT" to equip items to specific slots, rather than "right clicking" item upgrades using "CMSG_AUTOEQUIP_ITEM".
Fixes an issue with rings, trinkets and offhand weapons where the bot would only ever upgrade their first slot.

Also evaluate the above item types for equipping in both slots rather than just comparing to the first item.

Have tested with a range of rings of different itemlevels, as well as fury warrior (titan's grip) and rogue with daggers.

### CODE REVIEW

**Comment by Dreathean** [comment]
This is super awesome, nicely done!

**Comment by dedahr** [comment]
Hmm, now after this patch my all altbots keeps spamming if they have some weapon in inventory no matter what if it's an upg or not:
"equipping [weapon]"
"Item cannot be equipped"

**Comment by Bobblybook** [comment]
> Hmm, now after this patch my all altbots keeps spamming if they have some weapon in inventory no matter what if it's an upg or not: "equipping [weapon]" "Item cannot be equipped"
> 
> They also start to roll Need (y I have AiPlayerbot.LootRollLevel = 2) on weapons with stats totally out of their class (ie. mage and priest on dagger with STR STA DEF), all was fine yesterday.
> 
> On the other hand, AUTO replacing better 2nd ring do work.

Hm I wonder if it's a dual wield issue - do you see this with bot classes who can DW, or only casters? I think maybe 1h users are trying to get a second weapon for their offhand which is not possible for them to equip. I can test this tonight but if you have specific combinations of classes/items that have been giving errors, please let me know.

**Comment by dedahr** [comment]
> > Hmm, now after this patch my all altbots keeps spamming if they have some weapon in inventory no matter what if it's an upg or not: "equipping [weapon]" "Item cannot be equipped"
> > They also start to roll Need (y I have AiPlayerbot.LootRollLevel = 2) on weapons with stats totally out of their class (ie. mage and priest on dagger with STR STA DEF), all was fine yesterday.
> > On the other hand, AUTO replacing better 2nd ring do work.
> 
> Hm I wonder if it's a dual wield issue - do you see this with bot classes who can DW, or only casters? I think maybe 1h users are trying to get a second weapon for their offhand which is not possible for them to equip. I can test this tonight but if you have specific combinations of classes/items that have been giving errors, please let me know.

Got prot Warrior, ret Paladin, Holy Priest and Frost mage in party.

Warrior behave nice so far, but rest altbots got problem after I applied this patch. 

Currently just lvling in Outland so I just keep em auto roll NEED on upgrades weapons and stuff on the fly. They did that pretty good till patch except that 2nd ring and trinket, also q rewards was auto picked OK.

Don't have many examples for now (just playing 1h or so) but can give you two:
Priest and mage try to equip [Wild Wood Staff](https://www.wowhead.com/item=31414/wild-wood-staff) from quest [From the Ashes](https://www.wowhead.com/quest=10771/from-the-ashes) , I can understand why bots choose that reward (good sell, no other q rewards is worth to them), but now they just spam chat trying to eqip that.

Priest also NEEDed world drop [Draconic Dagger](https://www.wowhead.com/item=25107/draconic-dagger) so now trying to equip both staff and dagger one after another.

**Comment by avirar** [comment]
I've been tinkering with this issue for a few weeks. It's a mess, I need to refactor ItemUsageValue at the very least. EquipAction is working well though, and I've added a "qi [item link]" chat command to query item usage from a bot. Add non-combat strat "debug equip" and "debug roll" to enable more detail in the output of "qi" e.g result of CanUseItem, CanEquipItem, CanEquipWeapon, CanEquipArmor, the score from new and (both) existing items.

https://github.com/avirar/mod-playerbots/tree/equip_test

**Comment by Bobblybook** [comment]
> > > Hmm, now after this patch my all altbots keeps spamming if they have some weapon in inventory no matter what if it's an upg or not: "equipping [weapon]" "Item cannot be equipped"
> > > They also start to roll Need (y I have AiPlayerbot.LootRollLevel = 2) on weapons with stats totally out of their class (ie. mage and priest on dagger with STR STA DEF), all was fine yesterday.
> > > On the other hand, AUTO replacing better 2nd ring do work.
> > 
> > 
> > Hm I wonder if it's a dual wield issue - do you see this with bot classes who can DW, or only casters? I think maybe 1h users are trying to get a second weapon for their offhand which is not possible for them to equip. I can test this tonight but if you have specific combinations of classes/items that have been giving errors, please let me know.
> 
> Got prot Warrior, ret Paladin, Holy Priest and Frost mage in party (I'm MM hunter).
> 
> Warrior behave nice so far, but rest altbots got problem after I applied this patch.
> 
> Currently just lvling in Outland so I just keep em auto roll NEED on upgrades weapons and stuff on the fly. They did that pretty good till patch except that 2nd ring and trinket, also q rewards was auto picked OK.
> 
> Don't have many examples for now (just playing 1h or so) but can give you two: Priest and mage try to equip [Wild Wood Staff](https://www.wowhead.com/item=31414/wild-wood-staff) from quest [From the Ashes](https://www.wowhead.com/quest=10771/from-the-ashes) , I can understand why bots choose that reward (good sell, no other q rewards is worth to them), but now they just spam chat trying to eqip that.
> 
> Priest also NEEDed world drop [Draconic Dagger](https://www.wowhead.com/item=25107/draconic-dagger) so now trying to equip both staff and dagger one after another.
> 
> And chat spam example: 

Thanks, I'll add a dual-wield check and test with your examples tonight

**Comment by Bobblybook** [comment]
See new PR for fix, it did require dual-wield checks

**Comment by dedahr** [comment]
Y, all is ok now, many tx.

**Pull request merged**
