### PR TITLE
Shaman weapon buff fixes

### PR DESCRIPTION
**Pull request by Bobblybook**
- Fix endless loop for resto shamans trying to cast flametongue weap
- Add guard for offhand buffing to only buff weapons (no shields/offhand held items)

### CODE REVIEW

**Comment by liyunfan1223** [comment]
The action loop may be caused by the code here https://github.com/liyunfan1223/mod-playerbots/blob/9b1736e61f3c6a732c721d8045fca19531daf0d4/src/strategy/shaman/GenericShamanStrategy.cpp#L34C1 -L56C10

For the three funcs, it should be `/*A*/ nullptr`. The action place here should be an alternative action and should not be the same as itself. I can't test it myself currently. Maybe you can give it a try.

        static ActionNode* flametongue_weapon([[maybe_unused]] PlayerbotAI* botAI)
        {
            return new ActionNode ("flametongue weapon",
                /*P*/ nullptr,
                /*A*/ NextAction::array(0, new NextAction("flametongue weapon"), nullptr),
                /*C*/ nullptr);
        }


        static ActionNode* frostbrand_weapon([[maybe_unused]] PlayerbotAI* botAI)
        {
            return new ActionNode ("frostbrand weapon",
                /*P*/ nullptr,
                /*A*/ NextAction::array(0, new NextAction("frostbrand weapon"), nullptr),
                /*C*/ nullptr);
        }


        static ActionNode* windfury_weapon([[maybe_unused]] PlayerbotAI* botAI)
        {
            return new ActionNode ("windfury weapon",
                /*P*/ nullptr,
                /*A*/ NextAction::array(0, new NextAction("windfury weapon"), nullptr),
                /*C*/ nullptr);
        }

**Comment by Bobblybook** [comment]
> The action loop may be caused by the code here https://github.com/liyunfan1223/mod-playerbots/blob/9b1736e61f3c6a732c721d8045fca19531daf0d4/src/strategy/shaman/GenericShamanStrategy.cpp#L34C1 -L56C10
> 
> For the three funcs, it should be `/*A*/ nullptr`. The action place here should be an alternative action and should not be the same as itself. I can't test it myself currently. Maybe you can give it a try.
> 
> ```
>     static ActionNode* flametongue_weapon([[maybe_unused]] PlayerbotAI* botAI)
>     {
>         return new ActionNode ("flametongue weapon",
>             /*P*/ nullptr,
>             /*A*/ NextAction::array(0, new NextAction("flametongue weapon"), nullptr),
>             /*C*/ nullptr);
>     }
> 
> 
>     static ActionNode* frostbrand_weapon([[maybe_unused]] PlayerbotAI* botAI)
>     {
>         return new ActionNode ("frostbrand weapon",
>             /*P*/ nullptr,
>             /*A*/ NextAction::array(0, new NextAction("frostbrand weapon"), nullptr),
>             /*C*/ nullptr);
>     }
> 
> 
>     static ActionNode* windfury_weapon([[maybe_unused]] PlayerbotAI* botAI)
>     {
>         return new ActionNode ("windfury weapon",
>             /*P*/ nullptr,
>             /*A*/ NextAction::array(0, new NextAction("windfury weapon"), nullptr),
>             /*C*/ nullptr);
>     }
> ```

Thanks, this makes sense. I didn't realise these were alternatives, that would explain the flametongue loop.

I'll fill this out with alternatives that make sense and/or nulls and re-test tonight.

**Comment by Bobblybook** [comment]
This is now corrected, tested on:
- High level shaman, enh dual-wield
- High level shaman, resto, weapon+shield
- High level shaman, enh spec + heal strategy (edge case)
- Level 1 fresh shaman bots without trained spells
- Level 2 fresh shaman bots with rockbiter trained

All work as expected, I can no longer replicate any bugs.

**Comment by liyunfan1223** [comment]
Thank you for your effort!

**Pull request merged**
