### PR TITLE
FIX: "playerbots_names" table placed in the wrong database, has to be…

### PR DESCRIPTION
**Pull request by BenWagner-UX**
… in the PlayerBotsDatabase instead of CHaracterDatabase - This was causing a crash by make use of "addclass"

### CODE REVIEW

**Review by liyunfan1223 — CHANGES_REQUESTED** [review]
I guess "playerbots_names" table is placed in character database to prevent queries across multiple databases.

https://github.com/liyunfan1223/mod-playerbots/blob/17f416dc668907bf715b6ed57d3fc82c5b02796d/src/PlayerbotMgr.cpp#L895-L897

At the same time it is a bit troublesome to modify the database. You need to move the place of [playerbots_name.sql](https://github.com/liyunfan1223/mod-playerbots/blob/master/sql/characters/playerbots_names.sql) and ensure that the old version is updated correctly. I wonder if this is necessary.

**Comment by noisiver** [comment]
How exactly does this cause a crash when using addclass? I can't see having a table in a different database do that so I'd like to be enlightened.

**Comment by BenWagner-UX** [comment]
> How exactly does this cause a crash when using addclass? I can't see having a table in a different database do that so I'd like to be enlightened.

To reproduce:
Just remove the playerbots_names database from the character database and make use of "addclass".

Why I did this change:

The change is about separating concerns of each database, the "playerbots_names" doesnt belong to the CharactersDatabase of AzerothCore, it has to be a part of the PlayerBot Database as the name already suggests. Crossdatabase SELECTs are not a good way either but this is a different story we/someone have/has to address later.

**Comment by noisiver** [comment]
If you remove the table.. I mean, you could do that from the playerbots database as much as from the characters database. It makes more sense to me to keep important data in the characters database as you should never wipe that anyway.

**Comment by BenWagner-UX** [comment]
> If you remove the table.. I mean, you could do that from the playerbots database as much as from the characters database. Moving it solves nothing. It makes more sense to me to keep important data in the characters database as you should never wipe that anyway.

*playerbot*_names doesn't belong to the characters database of azerothcore, if everyone would work that way the servers databases would grow so fast with stuff that doen't belong there. Playerbots does have its own database - make use of it :)

Next example: In case I would like to transfer the data of the playerbot module to an another server, I have to pick up all those tables (at moment just 1) aside from the usual database dump.

Next example: It's causing confusion on the installation process. There are a plenty of scripts but no hint where to install (this was my original case which lead to the crash with addclass). I can browse through the code other with no experience in coding can't.

**Comment by noisiver** [comment]
1) A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.

2) That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.

3) It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.

Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.

You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.

This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.

**Comment by noisiver** [comment]
I guess it should be noted that it doesn't matter to me what is stored where. I only use altbots as "permanent" bots anyway so losing the playerbots database doesn't matter. It's uncertain weather this is a needed change or not and I wanted to give my 2 cents on the matter.

**Comment by BenWagner-UX** [comment]
> 1. A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.
> 2. That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.
> 3. It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.
> 
> Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.
> 
> You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.
> 
> This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.

" lot of modules store stuff in the characters database [...]" is no indication for being the right way or an excuse to violate the 

> 1. A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.
> 2. That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.
> 3. It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.
> 
> Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.
> 
> You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.
> 
> This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.

'The others do it the same way' is not an argument to violate the fundamental principles of software development. There are patterns like 'SoC' (Separation of Concerns) for a reason. The character database has NOTHING to do with how the Playerbot module assigns its names; that is simply NOT the responsibility of the character database. Even the naming schema is being violated here, which should already be an indication. Writing documentation to cover up fundamental oversights or decisions is also absolutely the wrong approach. Ideally, everything should work out-of-the-box, just like AzerothCore itself does.

**Comment by BenWagner-UX** [comment]
> I guess it should be noted that it doesn't matter to me what is stored where. I only use altbots as "permanent" bots anyway so losing the playerbots database doesn't matter. It's uncertain weather this is a needed change or not and I wanted to give my 2 cents on the matter.

The short answer: It does - Not for the computer hardware but for keeping the project maintainable.
Anyway, I appreciate your feedback and thank you for your 2 cents :)

**Comment by noisiver** [comment]
> > 1. A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.
> > 2. That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.
> > 3. It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.
> > 
> > Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.
> > You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.
> > This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.
> 
> " lot of modules store stuff in the characters database [...]" is no indication for being the right way or an excuse to violate the
> 
> > 1. A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.
> > 2. That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.
> > 3. It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.
> > 
> > Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.
> > You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.
> > This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.
> 
> 'The others do it the same way' is not an argument to violate the fundamental principles of software development. There are patterns like 'SoC' (Separation of Concerns) for a reason. The character database has NOTHING to do with how the Playerbot module assigns its names; that is simply NOT the responsibility of the character database. Even the naming schema is being violated here, which should already be an indication. Writing documentation to cover up fundamental oversights or decisions is also absolutely the wrong approach. Ideally, everything should work out-of-the-box, just like AzerothCore itself does.

You claim that playerbots doesn't work out of the box, but the argument is basically that someone deleted the table and the server crashes so it has to be changed.

You also ignore the fact that you want to move a table but completely ignore the other ones added by this module. Move them all or move none, it's really simple. It's just because this one caused a crash that it was brought to your attention.

Having an argument about `violating the fundamental principles of software development` yet you don't even acknowledge the fact that there are a total of 3 tables in the characters database and even 1 in the world database (excluding the added _dbc tables) but apparently those don't apply to your argument.

**Comment by BenWagner-UX** [comment]
> > > 1. A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.
> > > 2. That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.
> > > 3. It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.
> > > 
> > > Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.
> > > You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.
> > > This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.
> > 
> > 
> > " lot of modules store stuff in the characters database [...]" is no indication for being the right way or an excuse to violate the
> > > 1. A lot of modules store stuff in the characters database, stuff you don't want to lose. The fact that a database exists doesn't mean it has to be used for absolutely everything.
> > > 2. That doesn't make sense. If you transfer the playerbots database you would transfer the characters database too or `playerbots_random_bots` and `playerbots_names` serves no purpose in the move.
> > > 3. It's causing confusion because the user doesn't know how to do it or how it works exactly. The same could be said for any module, I would know after years of helping people with various modules. There is a wiki in development to help with that confusion.
> > > 
> > > Honestly, if you go into the characters database and start poking around it won't really matter what table you remove, it's either going to be a crash related to AzerothCore or Playerbots no matter what.
> > > You also seem to ignore the fact that there are actually more tables in the characters database. I guess they're not a concern because they haven't yet caused a crash.
> > > This is up to liyunfan in the end no matter what and I'll respect whatever the decision is.
> > 
> > 
> > 'The others do it the same way' is not an argument to violate the fundamental principles of software development. There are patterns like 'SoC' (Separation of Concerns) for a reason. The character database has NOTHING to do with how the Playerbot module assigns its names; that is simply NOT the responsibility of the character database. Even the naming schema is being violated here, which should already be an indication. Writing documentation to cover up fundamental oversights or decisions is also absolutely the wrong approach. Ideally, everything should work out-of-the-box, just like AzerothCore itself does.
> 
> You claim that playerbots doesn't work out of the box, but the argument is basically that someone deleted the table and the server crashes so it has to be changed.
> 
> You also ignore the fact that you want to move a table but completely ignore the other ones added by this module. Move all or move none, it's really simple. It's just because this one caused a crash that it was brought to your attention.
> 
> Having an argument about `violating the fundamental principles of software development` yet you don't even acknowledge the fact that there are a total of 3 tables in the characters database and even 1 in the world database (excluding the added _dbc tables) but apparently those don't apply to your argument.
> 
> Anyway, I'm dropping this now because it's just turning into a silly dispute. Liyunfan will decide and that's it. Lets just leave it at that.

"You claim that playerbots doesn't work out of the box, but the argument is basically that someone deleted the table and the server crashes so it has to be changed." 

Wrong, since there is no documentation  that reflect what table has to be placed where I accidentially created that table in the playerbots database because of its name. Logic move, isn't it? The server crashed 1 week later when the first player issued the "addclass" command.

"You also ignore the fact that you want to move a table but completely ignore the other ones added by this module. Move all or move none, it's really simple. It's just because this one caused a crash that it was brought to your attention."

And again, because of someone did it wrong in the past doesn't mean to do it wrong now or keep it that way especially when it leads to an crash - which why I am here. The creator of the mod didn't have created the database just for fun but for purpose.

"Having an argument about violating the fundamental principles of software development yet you don't even acknowledge the fact that there are a total of 3 tables in the characters database and even 1 in the world database (excluding the added _dbc tables) but apparently those don't apply to your argument."

I am here because of the "playerbot_names" table, because the wrong placement caused a crash and yes, I am not aware of the other tables. However, the same would go for them, when it doesn't apply to this: https://en.wikipedia.org/wiki/Separation_of_concerns (Please read.) but this is topic for an another day.

For me this isn't a silly dispute.

**Comment by Jgoodwin64** [comment]
> > I guess it should be noted that it doesn't matter to me what is stored where. I only use altbots as "permanent" bots anyway so losing the playerbots database doesn't matter. It's uncertain weather this is a needed change or not and I wanted to give my 2 cents on the matter.
> 
> The short answer: It does - Not for the computer hardware but for keeping the project maintainable. Anyway, I appreciate your feedback and thank you for your 2 cents :)

I agree that it should go in playerbots. For organization. I never look but assumed it was in the playerbots database already.

**Comment by liyunfan1223** [comment]
I appreciate all your comments, but most of them are out of scope. I'm just talking about the changes brought about by this PR. I should point out the fact that most users don't customize their database, so "playerbots_names" is placed in the character database by default so they don't suffer from such crashes. Conversely, if we merge it without modifying the repository, they will crash. This means that you must ensure that their database is modified when the code is modified, which is what this PR lacks.

Modification to the database is another issue. In my opinion, it's difficult to guarantee compatibility for every user, since you should consider both the data movement of old users and creation for new users. This is a risk with no explicit benefit and requires sufficient experience.

I'll close the PR, deferring this change until we have a more comprehensive understanding of the issue.

**Pull request closed without merging**
