### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by garfieldz90**
add bot loot method, they will join roll loots

### CODE REVIEW

**Comment by Dreathean** [comment]
Very cool addition. Do they check to see if it's an upgrade for them before rolling?

**Comment by garfieldz90** [comment]
> Very cool addition. Do they check to see if it's an upgrade for them before rolling?

no, im still learn how to do that, for now it just roll.

**Comment by liyunfan1223** [comment]
Introducing a configuration option to control the bot roll is a very nice change, thanks for your contribution!

Here are a few suggestions:

These lines of code that allow the bot to judge whether it needs the item and decide whether to roll it. https://github.com/liyunfan1223/mod-playerbots/pull/24/files#diff-133fd67b5765ee9bd6928a4359d93e436a09d13fa6ec79b8f8b62f594ab948a8R30-R59  
I tested his function before, but because I haven't decided how to add this function, so I commented it out. I suggest that you can combine the configuration options and whether items are needed to make to decide which method the bot roll.

**Comment by garfieldz90** [comment]
> Introducing a configuration option to control the bot roll is a very nice change, thanks for your contribution!
> 
> Here are a few suggestions:
> 
> These lines of code that allow the bot to judge whether it needs the item and decide whether to roll it. https://github.com/liyunfan1223/mod-playerbots/pull/24/files#diff-133fd67b5765ee9bd6928a4359d93e436a09d13fa6ec79b8f8b62f594ab948a8R30-R59 I tested his function before, but because I haven't decided how to add this function, so I commented it out. I suggest that you can combine the configuration options and whether items are needed to make to decide which method the bot roll.

哈哈谢谢大哥指点，我就是看不太懂这段代码的实现才这样写的，构思就是在配置文件里选择开启或关闭roll功能，希望大哥有空的话实现这个构思。我只是刚学了几天c++的菜鸟，有点难做到。

**Comment by liyunfan1223** [comment]
> > Introducing a configuration option to control the bot roll is a very nice change, thanks for your contribution!
> > Here are a few suggestions:
> > These lines of code that allow the bot to judge whether it needs the item and decide whether to roll it. https://github.com/liyunfan1223/mod-playerbots/pull/24/files#diff-133fd67b5765ee9bd6928a4359d93e436a09d13fa6ec79b8f8b62f594ab948a8R30-R59 I tested his function before, but because I haven't decided how to add this function, so I commented it out. I suggest that you can combine the configuration options and whether items are needed to make to decide which method the bot roll.
> 
> 哈哈谢谢大哥指点，我就是看不太懂这段代码的实现才这样写的，构思就是在配置文件里选择开启或关闭roll功能，希望大哥有空的话实现这个构思。我只是刚学了几天c++的菜鸟，有点难做到。

没关系，可以多尝试尝试。

**Pull request closed without merging**
