### PR TITLE
Fix transport movement

### PR DESCRIPTION
**Pull request by liyunfan1223**

### CODE REVIEW

**Comment by zhangbo8418** [comment]
Is this for repairing boats, elevators, flying trains, and subways? ? ? Someone fixed it before, but it broke again in recent updates.

**Comment by zhangbo8418** [comment]
There is also a robot that is broken when speaking other languages. I have a database here that uses GPT translation. It worked before, can you help test it? DBC.Locale = 4 in worldserver.conf

[playerbots_text.zip](https://github.com/user-attachments/files/16577466/playerbots_text.zip)

There is also a database in atidot3 pr.

[atidot3_playerbots_text.zip](https://github.com/user-attachments/files/16577477/atidot3_playerbots_text.zip)

**Comment by liyunfan1223** [comment]
It's unrelated to this change, please open a new issue.

> There is also a robot that is broken when speaking other languages. I have a database here that uses GPT translation. It worked before, can you help test it? DBC.Locale = 4 in worldserver.conf
> 
> [playerbots_text.zip](https://github.com/user-attachments/files/16577466/playerbots_text.zip)
> 
> There is also a database in atidot3 pr.
> 
> [atidot3_playerbots_text.zip](https://github.com/user-attachments/files/16577477/atidot3_playerbots_text.zip)

**Comment by zhangbo8418** [comment]
> _ No description provided. _

This thing has been fixed, but has it been completely fixed? For example, the subway cannot be ridden, and the death knight will not follow it on the ship.

**Pull request merged**
