### PR TITLE
Frost mage implementation

### PR DESCRIPTION
**Pull request by Bobblybook**
Hi,
Wondering if you can offer some advice on this.
I've worked on this yesterday, frost mage is now 90% working.

Procs are handled, rotation is handled, pet works.

Cold snap logic is not yet in, but the only issue I'm needing to fix is the deep freeze trigger is not working as intended.

I'm wanting to implement a 2-spell combo such as:

"If trigger, then cast frostbolt followed by deep freeze straight after".

The trigger is successfully being called, but I don't see this behaviour and deep freeze never gets cast.
I've verified the char has the skill learned.

The way I've implemented it is using a trigger with the continuer skill, set to deep freeze. Unsure if this is how I should be doing this, it may not work the way I think it does. Do you have any recommendations on how to set this up?

### CODE REVIEW

**Comment by liyunfan1223** [comment]
As far as I know, the implementation of 2-spell combo you wrote works. Maybe it's just that frostbolt consumes fingers of frost aura, thus making deep freeze unable to cast? You can check the logs to find out why, e.g. `grep "deep freeze" Playerbots.log`, there are probably logs about the reason for the failure. BTW, why did you make this spell combo haha, I'm not familiar with frost mage, does that make a higher dps?

**Comment by Bobblybook** [comment]
> As far as I know, the implementation of 2-spell combo you wrote works. Maybe it's just that frostbolt consumes fingers of frost aura, thus making deep freeze unable to cast? You can check the logs to find out why, e.g. `grep "{spellID of deep freeze}" Playerbots.log`, there are probably logs about the reason for the failure. BTW, why did you make this spell combo haha, I'm not familiar with frost mage, does that make a higher dps?

Ok thanks - I was checking the logs and I couldn't actually see it being cast. There is reference to the first frostbolt with weight 20, but nothing comes after.
I'll take another look today and maybe swap it out for fire blast temporarily to see where it's going wrong.

Yes, it's a core part of playing frost mage - you get two stacks of FoF, but the stack doesn't get consumed until your spells hit, so for the final stack, you weave in a fast hitting spell before the second frostbolt lands (ice lance, or deep freeze if it's off cd). Both spells benefit from the buff so you can effectively use the last stack twice, you are basically getting 50% more fingers of frost stacks doing this.
It's a pretty core part of playing frost mage and it doesn't seem very difficult logic to implement so I figured I'd give it a go.

**Comment by aronkleinhans** [comment]
There's this in the config

# Delay between two short-time spells cast
AiPlayerbot.GlobalCooldown = 500

Could be messing with the combo. I didn't check but I guess the delay triggers after the cast is done, there'd be no point to the delay anyway. 500ms is enough for the FB to land, and so it consumes the fof stack.

**Comment by Bobblybook** [comment]
> There are these in the config
> 
> Delay between two short-time spells cast AiPlayerbot.GlobalCooldown = 500
> 
> Delay between two bot actions AiPlayerbot.ReactDelay = 100
> 
> Could be messing with the combo. I didn't check but I guess the delay triggers after the cast is done, there'd be no point to the delay anyway. 100-500ms could be enough for the FB to land, and so it consumes the fof stack.

That's fine, this shouldn't matter I don't think.

After much digging, I can't find any way to make the continuer action thing do anything at all. Not sure if it's actually implemented to be honest..
I realised that adding multiple actions to the array effectively queues them and seems to work perfectly.

See PR, I believe this is now done, works very well, this frost mage is now a bit of a beast!
Can be merged and closed if no other changes needed

**Pull request merged**
