### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by garfieldz90**
1.bot will do skinning
2.bot will roll need or greed ,if item is good.
3.correct arg ShootDistance -> ShooterAviodDistance

### CODE REVIEW

**Comment by garfieldz90** [comment]
@liyunfan1223 report: i gave bot skining knife and learn skill skining, then they do skining. once they leave me few time and i invite bot return my party, they lose skining knife and never do skining, i wonder how to initialize they get skill equipment if they has skill, or just not delete the skill equipment.

**Comment by liyunfan1223** [comment]
> @liyunfan1223 report: i gave bot skining knife and learn skill skining, then they do skining. once they leave me few time and i invite bot return my party, they lose skining knife and never do skining, i wonder how to initialize they get skill equipment if they has skill, or just not delete the skill equipment.

Sorry to reply only now. First of all thank you for your contribution! 

Regarding skinning skills and skinning knives: The server will periodically initialize random bots (including when they level up, if the relevant settings are enabled), causing skills and items to be cleared. If you want to modify the skills and items during initialization, you need to pay attention to PlayerbotFactory::Randomize and PlayerbotFactory::Refresh and the functions called in them.

What I want to remind by the way is that you can split the modification of different parts into multiple PRs, and only modify the necessary code parts in the commit, so as to avoid inadvertently introducing other problems. The changes to skinning and rolls are really nice, and I'll merge them into the branch after further polishing and making sure it's working correctly.

**Comment by garfieldz90** [comment]
> > @liyunfan1223 report: i gave bot skining knife and learn skill skining, then they do skining. once they leave me few time and i invite bot return my party, they lose skining knife and never do skining, i wonder how to initialize they get skill equipment if they has skill, or just not delete the skill equipment.
> 
> Sorry to reply only now. First of all thank you for your contribution!
> 
> Regarding skinning skills and skinning knives: The server will periodically initialize random bots (including when they level up, if the relevant settings are enabled), causing skills and items to be cleared. If you want to modify the skills and items during initialization, you need to pay attention to PlayerbotFactory::Randomize and PlayerbotFactory::Refresh and the functions called in them.
> 
> What I want to remind by the way is that you can split the modification of different parts into multiple PRs, and only modify the necessary code parts in the commit, so as to avoid inadvertently introducing other problems. The changes to skinning and rolls are really nice, and I'll merge them into the branch after further polishing and making sure it's working correctly.
sure!

**Comment by Dreathean** [comment]
> Regarding skinning skills and skinning knives: The server will periodically initialize random bots (including when they level up, if the relevant settings are enabled), causing skills and items to be cleared. If you want to modify the skills and items during initialization, you need to pay attention to PlayerbotFactory::Randomize and PlayerbotFactory::Refresh and the functions called in them.
>
Hey Liyunfan, first of all you are a legend. Secondly, can you elaborate a little bit more on the server periodically initializing random bots? I am struggling to understand the extent of some of these intervals in the .conf, I assume those are the settings you are referring to? My main concern is preventing randombots from being wiped or wiping their inventory/gear as I ultimately want a set amount of bots that level up and gear up themselves and retain their progression and identity.

If I understand correctly, does the "AiPlayerbot.Min/MaxRandomBotRandomizeTime" control the function which periodically "initilalizes" or randomizes bots and if so would setting the min and max both to 0 prevent bots from having their skills/gear/inventory refreshed?

Thank you for all of your effort and contributions to this project!

image

**Comment by liyunfan1223** [comment]
@Dreathean  In design, the random bot is more like a one-time, short-term use, so the equipments and items will be casually initialized. Perhaps what you need more is to add a function that allows the character created by the player to be automatically controlled  by the bot system and level up themselves.

If desired, an additional option can be added to control whether random bots are initialized periodically. But simply disabling random bot initialization could lead to unexpected issues like bag being stuffed with loot, so I think adding the functions mentioned above is a better way. Of course, it is not that simple to implement that, and there are many details to be determined.

**Comment by Dreathean** [comment]
Gotcha, thank you for the clarification! I know this isn't the best place for this discussion. I guess during the level up process the system as is is likely ideal, but my main concern would be when approaching raiding, ie for example reaching level 60 (and capping level to 60) and doing 40 man raids with the playerbots, wanting to gear them up with raid loot we achieve and make sure that gear doesn't get replaced by an automatic process. Bags being wiped isn't a concern assuming they have already equipped the new raid gear. Is that something that might be feasible in the future? Something like: At level cap, continue bag initialization/refresh but halt equipment initialization/refresh?

Let me know if you want me to make this a separate Issue for discussion or to move this to the Discord. Thank you!

**Comment by garfieldz90** [comment]
> > Gotcha, thank you for the clarification! I know this isn't the best place for this discussion. I guess during the level up process the system as is is likely ideal, but my main concern would be when approaching raiding, ie for example reaching level 60 (and capping level to 60) and doing 40 man raids with the playerbots, wanting to gear them up with raid loot we achieve and make sure that gear doesn't get replaced by an automatic process. Bags being wiped isn't a concern assuming they have already equipped the new raid gear. Is that something that might be feasible in the future? Something like: At level cap, continue bag initialization/refresh but halt equipment initialization/refresh?
> > Let me know if you want me to make this a separate Issue for discussion or to move this to the Discord. Thank you!
> 
> Yeah we can create a issue to discuss further. I think your description makes sense and we can figure out how to get it done.

大哥，我需要关闭这个rp吗？还是留给你有空在看看代码在决定如何合并？

**Pull request closed without merging**
