### PR TITLE
World buff

### PR DESCRIPTION
**Pull request by kadeshar**
- added spec configuration for world buffs
- added world buffs to configuration file
- fixed NeedWorldBuffTrigger

### CODE REVIEW

**Comment by dedahr** [comment]
Dunno if it's relevant but in patch is missing one DK spec **Double aura blood**

**Comment by noisiver** [comment]
This is an amazing addition. I assume each comma-separated value is the spell id of a flask, elixir, food, etc and you can add as many as you want?

**Comment by kadeshar** [comment]
1. About DK spec sadly in current implementation i only checking with spec tab have most points in tree (using currently existing method)
2. Yes, you can add your own spellId (aura id more precisly)

**Comment by dedahr** [comment]
> 1. About DK spec sadly in current implementation i only checking with spec tab have most points in tree (using currently existing method).
> 

It will be fine as it is variant of blood for Boss tanking so Stoneblood flask is ok as it has more blood points just as blood spec.
So i presume this will be used no matter that exact spec is missing, right ?

**Comment by kadeshar** [comment]
> > 1. About DK spec sadly in current implementation i only checking with spec tab have most points in tree (using currently existing method).
> 
> It will be fine as it is variant of blood for Boss tanking so Stoneblood flask is ok as it has more blood points just as blood spec. So i presume this will be used no matter that exact spec is missing in config, right ?

If second build have most points in blood tree then yes :)

**Comment by Bobblybook** [comment]
> > > 1. About DK spec sadly in current implementation i only checking with spec tab have most points in tree (using currently existing method).
> > 
> > 
> > It will be fine as it is variant of blood for Boss tanking so Stoneblood flask is ok as it has more blood points just as blood spec. So i presume this will be used no matter that exact spec is missing in config, right ?
> 
> If second build have most points in blood tree then yes :)

Both of those blood specs are for tanking so should use the same consumables, shouldn't be an issue.
It gets more complicated if someone adds a blood dps spec, which do exist. You can still identify the role based on specific talent picks if you're crafty.

Same goes with Feral druid cat vs. bear spec. They are both deep feral tree specs, however you can use specific talents to identify the role.

I have a druid bot that has dual spec [Feral dps](https://www.wowhead.com/wotlk/talent-calc/druid/-543202132322010053120030310511-203503012_001ngz11nh221xjf31rfz41stk51rg1) and [Feral tank](https://www.wowhead.com/wotlk/talent-calc/druid/-503232132322010353120300313511-20350001_001ngv11ngx21zpv31rg241rg651rfz) and playerbots successfully identifies them as dps and tank roles when I switch, I'm guessing it's based off Thick Hide or something like that.

**Comment by kadeshar** [comment]
> > > > 1. About DK spec sadly in current implementation i only checking with spec tab have most points in tree (using currently existing method).
> > > 
> > > 
> > > It will be fine as it is variant of blood for Boss tanking so Stoneblood flask is ok as it has more blood points just as blood spec. So i presume this will be used no matter that exact spec is missing in config, right ?
> > 
> > 
> > If second build have most points in blood tree then yes :)
> 
> Both of those blood specs are for tanking so should use the same consumables, shouldn't be an issue. It gets more complicated if someone adds a blood dps spec, which do exist. You can still identify the role based on specific talent picks if you're crafty.
> 
> Same goes with Feral druid cat vs. bear spec. They are both deep feral tree specs, however you can use specific talents to identify the role.
> 
> I have a druid bot that has dual spec [Feral dps](https://www.wowhead.com/wotlk/talent-calc/druid/-543202132322010053120030310511-203503012_001ngz11nh221xjf31rfz41stk51rg1) and [Feral tank](https://www.wowhead.com/wotlk/talent-calc/druid/-503232132322010353120300313511-20350001_001ngv11ngx21zpv31rg241rg651rfz) and playerbots successfully identifies them as dps and tank roles when I switch, I'm guessing it's based off Thick Hide or something like that.

This druid recognize its hardcoded. But I didnt thought about using "talents spec" command. This command somehow can match bot with build. I will think about that in next iteration also with lower than 80lvl buffs (such list exists in cmangos playerbots)
obraz
obraz
https://github.com/celguar/spp-classics-cmangos/blob/master/Settings/tbc/aiplayerbot.conf

**Pull request merged**
