### PR TITLE
Fix .playerbot bot self

### PR DESCRIPTION
**Pull request by liyunfan1223**
This PR introduces some crucial changes, so I will keep it open for several days to monitor for any bugs that may arise. You are welcome to test it and provide feedback.

- Fixed `.playerbot bot self` command. Typing this command again to break. 
  - Closes https://github.com/liyunfan1223/mod-playerbots/issues/249.
- Fixed selling failure issue.
- Fixed a possible crash caused by invites.
  - https://github.com/liyunfan1223/mod-playerbots/issues/321#issuecomment-2235336394
- Fixed an addclass issue caused by decreasing RandomBotAccountCount.

### CODE REVIEW

**Comment by Jgoodwin64** [comment]
Tested and it works well, thanks for the effort. Still testing it. The command toggles well and I have not had the group with myself error.

**Comment by Jgoodwin64** [comment]
I tested to see if I could still do " playerbot bot add [Name] " while being bot self-ed. If I did it correctly, the bug where you could not add bots or sometimes could not add bot, is gone. 
There is still an issue occasionally with .summon. Only sometimes, when you try .summon a player by targeting the party member, It will give an error. I also got an error once or twice saying that player is not online but it was clearly online.  This was all while bot self was on. It always turned off for me when I tried, and without any weirdness.

**Comment by Jgoodwin64** [comment]
After further testing it seems the self bot doesn't want to walk by it's self anymore. Before, I would tell it stay and then I could take over walking now, I can't get it to walk to grind or do quests.

**Comment by voarsh2** [comment]
> After further testing it seems the self bot doesn't want to walk by it's self anymore. Before, I would tell it stay and then I could take over walking now, I can't get it to walk to grind or do quests. Upon further, further testing. I see that when the targets are close enough the selfbot works fine. It is only getting to the area that is the issue.

Yh. It doesn't walk around when using selfbot

**Pull request merged**
