### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by garfieldz90**
1. rewrite roll for loot: bot will compare equip with loot, pick batter one.
2. add new flee method, i name it "safe flee": bot will flee in combat if his health low and try avoid enemy, return group if safe.
3. bot not teleport after level up if he is in group. 

@liyunfan1223 我已经用gdb测试代码了，测试时间：游玩1小时，通宵挂着服务器8个小时，并没有导致游戏服务意外停止的情况。请酌情合并呗！

### CODE REVIEW

**Comment by garfieldz90** [comment]
> First of all, I think the changes are very good, but they still need to be discussed before they are merged (I suggest that we can make these discussions in the form of issues first, and then submit a PR after reaching confirmation).
> 
>     1. Will the "safe flee" strategy triggered at unnecessary times, especially for bosses with special mechanisms, such as Gluth of Naxx? I think it's best not to add this policy by default.
> 
>     2. Increase the bot’s movement speed through SetSpeed. This is cheating to some extent and I think it should be avoided as much as possible.
> 
> 
> I have been busy with other things recently and may not be able to maintain it in time. We can conduct subsequent development in the repository https://github.com/ZhengPeiRu21/mod-playerbots, and I will also transfer subsequent development there.

那么去除掉safe flee 这个trigger。 我还对panic和outnumberd这两个triggers进行了重写，你如果有空的话看看我写的是否合理， [510199f](https://github.com/liyunfan1223/mod-playerbots/pull/35/commits/510199fd3b30811baaa21484f2f46a629fa8b4fc), [4d25b8d](https://github.com/liyunfan1223/mod-playerbots/pull/35/commits/4d25b8d04080670eb5c78ebc7d8dd36f45f11fa0)不行的话我取消修改。

**Comment by liyunfan1223** [comment]
@garfieldz90 Sorry for the late reply. I have recently been considering adding the function of the auto equipment rolling into the mod. Are you interested in submitting a separate PR for this function? This PR seems to involve too many functions, so we can try to split it into multiple PRs.

**Comment by garfieldz90** [comment]
> @garfieldz90 Sorry for the late reply. I have recently been considering adding the function of the auto equipment rolling into the mod. Are you interested in submitting a separate PR for this function? This PR seems to involve too many functions, so we can try to split it into multiple PRs.

我非常感兴趣，但是由于很长一段时间在忙碌，没有再继续贡献代码了，之前我写的自动装备roll到的装备的源代码也搞丢了，不知道怎么弄回来。

**Comment by nl-saw** [comment]
Nice proposed changes. Would also be great if they move out of AOE and nut just stand there like dumb-asses.

**Pull request closed without merging**
