### PR TITLE
Bot questing fixes

### PR DESCRIPTION
**Pull request by atidot3**
Bot should be way more consistent and accurate at doing quests.
Add missing implementation of update kill / update loot on quests.
Add "debug quest" strategy to allow debugging.

image
image
image
image

Known issue:
Gameobject quest arent functionnal yet
Quest item use on NPC doesnt seem to be implemented

### CODE REVIEW

**Comment by atidot3** [comment]
Quest [ Your Place In The World ] accepted
Quest [ A Humble Task ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ Vile Familiars ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ A Humble Task ] accepted
Quest [ Dolanaar Delivery ] accepted
Quest [ A Threat Within ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ A Humble Task ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Rest and Relaxation ] accepted
Quest [ Supplies to Tannok ] accepted
Quest [ A Humble Task ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ A Threat Within ] accepted
Quest [ A Threat Within ] accepted
Quest [ The Troll Cave ] accepted
Quest [ A Humble Task ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ A Threat Within ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Dolanaar Delivery ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ A Humble Task ] accepted
Quest [ Your Place In The World ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ Supplies to Tannok ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Supplies to Tannok ] accepted
Quest [ A Humble Task ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ A Threat Within ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ Kobold Camp Cleanup ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Troll Cave ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ A Threat Within ] accepted
Quest [ Supplies to Tannok ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ Rest and Relaxation ] accepted
Quest [ A Humble Task ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ A Humble Task ] accepted
Quest [ A Threat Within ] accepted
Quest [ Dolanaar Delivery ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Troll Cave ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ A Humble Task ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Rest and Relaxation ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ A Humble Task ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Your Place In The World ] accepted
Quest [ A Humble Task ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Supplies to Tannok ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Troll Cave ] accepted
Quest [ A Threat Within ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Your Place In The World ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ A Humble Task ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ Dolanaar Delivery ] accepted
Quest [ The Pools of Aggonar ] accepted
Quest [ Swoop Hunting ] accepted
Quest [ The Balance of Nature ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ The Troll Cave ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Welcome to the Jungle ] accepted
Quest [ Rest and Relaxation ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ Your Place In The World ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Hunt Begins ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ The Grimtotem Weapon ] accepted
Quest [ Your Place In The World ] accepted
Quest [ Dwarven Outfitters ] accepted
Quest [ The Mindless Ones ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ Rest and Relaxation ] accepted
Quest [ A Threat Within ] accepted
Quest [ Cutting Teeth ] accepted
Quest [ The Woodland Protector ] accepted
Quest [ A Humble Task ] accepted
Quest [ A Threat Within ] accepted
Quest [ Rest and Relaxation ] accepted
Quest [ A Humble Task ] accepted

**Comment by noisiver** [comment]
This is great. Good job!

**Comment by atidot3** [comment]
There's still so much to do with quests its insane :')

**Comment by Dreathean** [comment]
Awesome stuff! Thank you for your contribution!

**Comment by noisiver** [comment]
I'm testing it now, will merge your recent commit and reset the bots. They're not talking at all though, not sure why. Anyway, how would you currently enable them to /say what they're doing with quests?

**Comment by atidot3** [comment]
you need to add them "debug quest" strategy in the cfg yes

**Comment by atidot3** [comment]
i've been trying to force them to ONLY do quests but tbh i've no idea itf its even possible

**Comment by noisiver** [comment]
It has to be. It would be a nice feature to have, although it shouldn't be enabled by default if so because it limits them in other ways. All their actions are pre-determined so telling them to only do quests has to be possible, somehow.

**Comment by atidot3** [comment]
no not all the time, but for testing so they only make quests

**Comment by noisiver** [comment]
After letting the server run for a while, this happens. Now the server crashes as soon as the bots log in.

[gdb.txt](https://github.com/user-attachments/files/16430976/gdb.txt)

**Comment by atidot3** [comment]
# Randombots will group with nearby bots to do shared quests
AiPlayerbot.RandomBotGroupNearby = 0

This is my settings

**Comment by noisiver** [comment]
Yes but if it's crashing because of it being enabled, as a result of this PR, you have to fix it before it's merged though.

**Comment by atidot3** [comment]
Random list of completed quests:
Kynthia => Quest [ The Troll Cave ] completed
Eufamie => Quest [ A Fishy Peril ] completed
Sansalas => Quest [ Cutting Teeth ] completed
Phylypp => Quest [ The Boar Hunter ] completed
Igaratza => Quest [ A Threat Within ] completed
Gauargi => Quest [ The Woodland Protector ] completed
Cyncus => Quest [ Tools for Steelgrill ] completed
Arnaud => Quest [ Rest and Relaxation ] completed
Pertesia => Quest [ The Woodland Protector ] completed
Aeduin => Quest [ A Fishy Peril ] completed
Sibota => Quest [ A Threat Within ] completed
Alpaida => Quest [ Your Place In The World ] completed
Melissa => Quest [ The Hunt Begins ] completed
Atymnius => Quest [ Dwarven Outfitters ] completed
Halinard => Quest [ The Woodland Protector ] completed
Eylgar => Quest [ Rest and Relaxation ] completed
Jellfte => Quest [ Rest and Relaxation ] completed
Petrona => Quest [ The Balance of Nature ] completed
Italia => Quest [ Tainted Scroll ] completed
Richelda => Quest [ The Hunt Begins ] completed
Herenborg => Quest [ A Threat Within ] completed
Petrona => Quest [ The Woodland Protector ] completed
Stephane => Quest [ The Mindless Ones ] completed
Helgesippos => Quest [ The Mindless Ones ] completed
Jonathas => Quest [ The Woodland Protector ] completed
Theodoracius => Quest [ The Balance of Nature ] completed
Leontia => Quest [ The Balance of Nature ] completed
Epicaste => Quest [ The Balance of Nature ] completed
Igaratza => Quest [ Eagan Peltskinner ] completed
Ailiet => Quest [ The Hunt Begins ] completed
Amalasuintha => Quest [ Rest and Relaxation ] completed
Annaple => Quest [ The Mindless Ones ] completed
Lois => Quest [ The Mindless Ones ] completed
Xanthippus => Quest [ Rest and Relaxation ] completed
Hildberta => Quest [ The Hunt Begins ] completed
Gilpin => Quest [ Cutting Teeth ] completed
Antichares => Quest [ The Mindless Ones ] completed
Annaple => Quest [ Glyphic Scroll ] completed
Liuiua => Quest [ Rest and Relaxation ] completed
Phoenix => Quest [ Rest and Relaxation ] completed
Ailiet => Quest [ Verdant Note ] completed
Juet => Quest [ A Humble Task ] completed
Emelyne => Quest [ The Damned ] completed
Truffeni => Quest [ A Threat Within ] completed
Atotz => Quest [ The Woodland Protector ] completed
Harding => Quest [ Verdant Note ] completed
Bacchides => Quest [ The Mindless Ones ] completed
Bodolev => Quest [ The Troll Cave ] completed
Odriana => Quest [ Rune-Inscribed Note ] completed
Prothesia => Quest [ The Balance of Nature ] completed
Grisigion => Quest [ The Hunt Begins ] completed
Halinard => Quest [ The Balance of Nature ] completed
Cyncus => Quest [ Stocking Jetsteam ] completed
Aide => Quest [ The Mindless Ones ] completed
Mirield => Quest [ Rest and Relaxation ] completed
Aimar => Quest [ A Little Luck ] completed
Gresilda => Quest [ Cutting Teeth ] completed
Estramarin => Quest [ The Hunt Begins ] completed
Egina => Quest [ Your Place In The World ] completed
Gomeric => Quest [ A Threat Within ] completed
Ratier => Quest [ Rest and Relaxation ] completed
Clementia => Quest [ Meats to Orgrimmar ] completed
Ripertus => Quest [ Dwarven Outfitters ] completed
Belaskita => Quest [ Encrypted Sigil ] completed
Hitzeder => Quest [ Cutting Teeth ] completed
Rosaline => Quest [ The Balance of Nature ] completed
Wymer => Quest [ Cutting Teeth ] completed
Brien => Quest [ Check Up on Tabetha ] completed
Isott => Quest [ The Damned ] completed
Gifford => Quest [ The Hunt Begins ] completed
Grisigion => Quest [ Verdant Note ] completed
Kassandra => Quest [ The Troll Cave ] completed
Lohitzun => Quest [ The Balance of Nature ] completed
Tiro => Quest [ The Mindless Ones ] completed
Anteia => Quest [ Dwarven Outfitters ] completed
Lavin => Quest [ The Mindless Ones ] completed
Arculf => Quest [ Dwarven Outfitters ] completed
Grisigion => Quest [ A Humble Task ] completed
Jonathas => Quest [ The Balance of Nature ] completed
Jakelin => Quest [ The Damned ] completed
Odlenda => Quest [ A Peon's Burden ] completed
Sibly => Quest [ The Balance of Nature ] completed
Estebeni => Quest [ The Woodland Protector ] completed
Tiro => Quest [ Hallowed Scroll ] completed
Presebal => Quest [ A Fishy Peril ] completed
Hermongenes => Quest [ The Hunt Begins ] completed
Legarda => Quest [ The Balance of Nature ] completed
Ethelmar => Quest [ Rest and Relaxation ] completed
Polyxeinus => Quest [ Tainted Scroll ] completed
Odo => Quest [ The Damned ] completed
Antichares => Quest [ Hallowed Scroll ] completed
Alpaida => Quest [ Cutting Teeth ] completed
Picot => Quest [ Kobold Camp Cleanup ] completed
Antonius => Quest [ Stocking Jetsteam ] completed
Mirella => Quest [ Cutting Teeth ] completed
Kriton => Quest [ Dwarven Outfitters ] completed
Amane => Quest [ The Hunt Begins ] completed
Helissente => Quest [ Your Place In The World ] completed
Helgesippos => Quest [ Tainted Scroll ] completed
Aileth => Quest [ Rest and Relaxation ] completed
Arianna => Quest [ Scalding Mornbrew Delivery ] completed
Agas => Quest [ Stocking Jetsteam ] completed
Hildberta => Quest [ Verdant Note ] completed
Hegesistrato => Quest [ The Damned ] completed
Leontia => Quest [ The Woodland Protector ] completed
Ision => Quest [ A Good Friend ] completed
Inge => Quest [ Plants of Zangarmarsh ] completed
Mainet => Quest [ The Boar Hunter ] completed

**Comment by atidot3** [comment]
New commit require core changes to be able to compile
https://github.com/liyunfan1223/azerothcore-wotlk/pull/18

**Comment by zhangbo8418** [comment]
Can the default conversation language of the robot be controlled through the configuration file?

**Comment by atidot3** [comment]
Bot default conversation is using the config DBC locale.
There is some hardcoded english chat line but most of it is using mysql entry that contains translation so you should be fine

**Comment by atidot3** [comment]
This last commit should be working now without any more crashes.

**Comment by liyunfan1223** [comment]
Thank you @atidot3. Could you check the warning here https://github.com/liyunfan1223/azerothcore-wotlk/pull/18#discussion_r1699642879

**Comment by liyunfan1223** [comment]
I appreciate your effort, but I have to say that these changes involve so much that I can't start a code review. Aside from extensive testing, I can't guarantee they won't break existing functionality.

**Comment by atidot3** [comment]
No probs, allowing bot to handle quests was indeed going to change alot of thing as the mod/core was missing some implementation and i had to rework some feature as bot questing in group was making few crashes.

My dedicated is running this PR for while now and i havent seen ( so far ) any changes in functionnality, been doing BGs and Dungeon / Raid, bot still uses their items move to location randomly kill enemy for grinding etc.

The only issue so far i have made is now all bots have full quest log im trying to make a patch to allow them to drop quests that they dont have any interest in anymore

**Comment by liyunfan1223** [comment]
I'm happy to see new features being added, but as a maintainer it's more important that I make sure existing features don't break or cause additional crashes before I introduce new features. Testing is certainly one method, but testing is not comprehensive, because different people run the server in different ways, and one person's testing cannot cover all situations.

We need to "prove" together that it will not introduce new issues. If the scope of the modified code is small and the function is clear, it will be easier to implement, but vice versa is very difficult.

**Comment by atidot3** [comment]
Yea yea ofc sorry i didnt meant to say like i tested it its working pardon my english !

**Comment by noisiver** [comment]
Changes not related to quests should've been their own PR. This is why you don't commit to and PR from the master branch. Separate branches for these changes would've been easier.

**Comment by atidot3** [comment]
image
image
image

Bot will always try to keep a certain amount of quests in their log grey / green / red but if they have more than 15 quests they will start to cleanup quests based on priority.

This action will not be performed automatically if the bot has a master.

**Comment by zhangbo8418** [comment]
> image image image
> 
> Bot will always try to keep a certain amount of quests in their log grey / green / red but if they have more than 15 quests they will start to cleanup quests based on priority.
> 
> This action will not be performed automatically if the bot has a master.
> 
> This should conclude this PR with lots of crash related to group and chatting with bots performing quests action in party.


A bunch of warnings


In file included from /azerothcore/modules/mod-playerbots/src/PlayerbotAI.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/TankWarriorStrategy.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.cpp:9:
/azerothcore/src/server/game/Chat/Chat.h:66:88: warning: argument 1 null where non-null expected [-Wnonnull]
   66 |             ObjectGuid const& senderGuid = ObjectGuid(), std::string_view senderName = nullptr,
      |                                                                                        ^~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /azerothcore/src/common/Common.h:22,
                 from /azerothcore/modules/mod-playerbots/src/strategy/AiObjectContext.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.cpp:5:
/usr/include/c++/11/string_view:131:7: note: in a call to function ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>]’ declared ‘nonnull’
  131 |       basic_string_view(const _CharT* __str) noexcept
      |       ^~~~~~~~~~~~~~~~~
In file included from /azerothcore/modules/mod-playerbots/src/PlayerbotAI.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/TankWarriorStrategy.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.cpp:9:
/azerothcore/src/server/game/Chat/Chat.h:67:88: warning: argument 1 null where non-null expected [-Wnonnull]
   67 |             ObjectGuid const& targetGuid = ObjectGuid(), std::string_view targetName = nullptr,
      |                                                                                        ^~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /azerothcore/src/common/Common.h:22,
                 from /azerothcore/modules/mod-playerbots/src/strategy/AiObjectContext.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.cpp:5:
/usr/include/c++/11/string_view:131:7: note: in a call to function ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>]’ declared ‘nonnull’
  131 |       basic_string_view(const _CharT* __str) noexcept
      |       ^~~~~~~~~~~~~~~~~
In file included from /azerothcore/modules/mod-playerbots/src/PlayerbotAI.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/TankWarriorStrategy.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.cpp:9:
/azerothcore/src/server/game/Chat/Chat.h:68:44: warning: argument 1 null where non-null expected [-Wnonnull]
   68 |             std::string_view channelName = nullptr, uint32 achievementId = 0);
      |                                            ^~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /azerothcore/src/common/Common.h:22,
                 from /azerothcore/modules/mod-playerbots/src/strategy/AiObjectContext.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorAiObjectContext.cpp:5:
/usr/include/c++/11/string_view:131:7: note: in a call to function ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>]’ declared ‘nonnull’
  131 |       basic_string_view(const _CharT* __str) noexcept
      |       ^~~~~~~~~~~~~~~~~
In file included from /azerothcore/modules/mod-playerbots/src/PlayerbotAI.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.cpp:5:
/azerothcore/src/server/game/Chat/Chat.h:66:88: warning: argument 1 null where non-null expected [-Wnonnull]
   66 |             ObjectGuid const& senderGuid = ObjectGuid(), std::string_view senderName = nullptr,
      |                                                                                        ^~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /azerothcore/src/common/Common.h:22,
                 from /azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/triggers/RangeTriggers.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/triggers/GenericTriggers.h:10,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.cpp:5:
/usr/include/c++/11/string_view:131:7: note: in a call to function ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>]’ declared ‘nonnull’
  131 |       basic_string_view(const _CharT* __str) noexcept
      |       ^~~~~~~~~~~~~~~~~
In file included from /azerothcore/modules/mod-playerbots/src/PlayerbotAI.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.cpp:5:
/azerothcore/src/server/game/Chat/Chat.h:67:88: warning: argument 1 null where non-null expected [-Wnonnull]
   67 |             ObjectGuid const& targetGuid = ObjectGuid(), std::string_view targetName = nullptr,
      |                                                                                        ^~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /azerothcore/src/common/Common.h:22,
                 from /azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/triggers/RangeTriggers.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/triggers/GenericTriggers.h:10,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.cpp:5:
/usr/include/c++/11/string_view:131:7: note: in a call to function ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>]’ declared ‘nonnull’
  131 |       basic_string_view(const _CharT* __str) noexcept
      |       ^~~~~~~~~~~~~~~~~
In file included from /azerothcore/modules/mod-playerbots/src/PlayerbotAI.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:9,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.cpp:5:
/azerothcore/src/server/game/Chat/Chat.h:68:44: warning: argument 1 null where non-null expected [-Wnonnull]
   68 |             std::string_view channelName = nullptr, uint32 achievementId = 0);
      |                                            ^~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /azerothcore/src/common/Common.h:22,
                 from /azerothcore/modules/mod-playerbots/src/PlayerbotAIConfig.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/triggers/RangeTriggers.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/triggers/GenericTriggers.h:10,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.h:8,
                 from /azerothcore/modules/mod-playerbots/src/strategy/warrior/WarriorTriggers.cpp:5:
/usr/include/c++/11/string_view:131:7: note: in a call to function ‘constexpr std::basic_string_view<_CharT, _Traits>::basic_string_view(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>]’ declared ‘nonnull’
  131 |       basic_string_view(const _CharT* __str) noexcept
      |       ^~~~~~~~~~~~~~~~~
In file included from /azerothcore/modules/mod-pvpscript/src/PvPScript.cpp:10:
/azerothcore/src/server/game/Chat/Chat.h:66:88: warning: argument 1 null where non-null expected [-Wnonnull]
   66 |             ObjectGuid const& senderGuid = ObjectGuid(), std::string_view senderName = nullptr,
      |                                                                                        ^~~~~~~

**Comment by atidot3** [comment]
im sorry but this is unmodified files did you mean to make an issue ?

**Pull request closed without merging**
