### PR TITLE
[Bugfix] reverted changes in need world buff trigger

### PR DESCRIPTION
**Pull request by kadeshar**
Reason:
https://github.com/liyunfan1223/mod-playerbots/issues/808

### CODE REVIEW

**Comment by hermensbas** [comment]
didnt you test it?

**Comment by kadeshar** [comment]
> didnt you test it?

Yes. But this previous version too and in windows environment both working.
I dont have linux arm development environment :(

**Comment by hermensbas** [comment]
Strange it only crashes in certain environments. :/

**Comment by noisiver** [comment]
> > didnt you test it?
> 
> Yes. But this previous version too and in windows environment both working. I dont have linux arm development environment :(

To be fair I switched to using my ARM setup only yesterday so I didn't catch it either.

I don't understand it either but at least it's fixed now. I've been running a few dungeons with worldbuff set and it works like a charm. Thank you for fixing this.

**Pull request merged**
