### PR TITLE
Add performance tuning in the overworld

### PR DESCRIPTION
**Pull request by brian8544**

### CODE REVIEW

**Comment by liyunfan1223** [comment]
Hello @brian8544. Is this modification completed?

**Comment by brian8544** [comment]
> Hello @brian8544. Is this modification completed?

I do _not_ know if this implementation was done correctly, so far it's all done (afaik), but **_please_** test & verify my code before pushing to main :)

**Comment by liyunfan1223** [comment]
Thank you for your reply. I'm thinking of implementing something similar, maybe in a different way.

**Comment by brian8544** [comment]
> Thank you for your reply. I'm thinking of implementing something similar, maybe in a different way.

You really should, it would improve performance around the player a lot :D

**Pull request closed without merging**
